stripe/stripe-terminal-react-native

- dev-app/ios/Podfile.lock
- example-app/ios/Podfile.lock
- example-app/package.json
- example-app/yarn.lock
Updating dev-app / example-app to beta-5 release
> post beta-5 updates and cleanup

- android/src/main/java/com/stripeterminalreactnative/Errors.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/Errors.swift
- ios/StripeTerminalReactNative.swift
resolves #349 
Prevent calling `discoverReaders` if the previous call is not completed or canceled to avoid losing reference of `cancelable`.
Select one:
> prevent calling discoverReaders if not completed

- dev-app/src/screens/DiscoverReadersScreen.tsx
beforeRemove navigation listener needs to be cleaned up and it has to take into account `connectingReader` in order to determine if `cancelDiscovering` should be called. e.g. it should not be called when a reader has been connected already.
Select one:
> beforeRemove listener cleanup

- android/build.gradle
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
iOS: 2.9.0 -> 2.11.0
android: 2.10.0 -> 2.12.0
New features will be wired up for usage in SDK in a following release.
KTLO
CI passes, 🚢 
Will publish change log on next npm release
> bumping underlying SDK versions

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/NativeTypeFactory.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/callback/NoOpCallback.kt
- android/src/main/java/com/stripeterminalreactnative/listener/RNDiscoveryListener.kt
- android/src/test/java/com/stripeterminalreactnative/listener/RNBluetoothReaderListenerTest.kt
- android/src/test/java/com/stripeterminalreactnative/listener/RNDiscoveryListenerTest.kt
- android/src/test/java/com/stripeterminalreactnative/listener/RNUsbReaderListenerTest.kt
Update Android's `discoverReaders` to properly resolve the passed in promise.
Also, fix an issue where our `discoverCancelable` could get stuck in a non-null
state, which caused any subsenquent calls to `discoverReaders` to fail with a
"busy" error.
PR is best reviewed commit-by-commit.
Fixes #371.
Select one:
TBD updating a CHANGELOG.
> [android][discoverReaders] Fix promise resolution

- android/src/main/java/com/stripeterminalreactnative/callback/NoOpCallback.kt
- android/src/main/java/com/stripeterminalreactnative/listener/RNDiscoveryListener.kt
Rather than using inheritance, let's delegate to the NoOpCallback.
No functional change.
https://github.com/stripe/stripe-terminal-react-native/pull/382#discussion_r981530550
> [android] RNDiscoveryListener: Delegate to NoOpCallback

- ios/StripeTerminalReactNative.swift
We want to mimic the behavior of the underlying native SDKs. This
change now matches how Android works, and it's also how the native iOS SDK
handles the completion block passed to `discoverReaders`.
Note that the underlying native SDKs behave differently for a user cancelation.
The Android SDK returns an error, and the iOS SDK returns a success.
Unify promise behavior at the RN layer.
Addresses:
https://github.com/stripe/stripe-terminal-react-native/issues/371#issuecomment-1260649238
Tested with this patch:
```
diff --git a/dev-app/src/screens/DiscoverReadersScreen.tsx b/dev-app/src/screens/DiscoverReadersScreen.tsx
index 418a59b..e88a48a 100644
--- a/dev-app/src/screens/DiscoverReadersScreen.tsx
+++ b/dev-app/src/screens/DiscoverReadersScreen.tsx
@@ -140,11 +140,13 @@ export default …
```
> [ios] Only resolve discoverReaders promise after callback

- scripts/publish.sh
Require that the developer provide a version string, rather than relying
on npm/yarn to do the right thing re: semantic versioning. Since we're
still in beta, it's easier that we manage our own version strings so
that, for example, `v0.0.1-beta.9` doesn't get revved up to `v0.0.1`
when passing `patch` as an argument.
Make publishing/releasing a bit less magical.
> scripts/publish: Don't support patch/minor/major

- android/build.gradle
- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bump SDK versions in preparation for new features.
I'll need to use the updated SDKs for tip-eligible amounts (coming in a later PR).
No major changes, but tested via building dev app on iOS / Android
Select one:
> Bump iOS to 2.13, Android to 2.14

- CODEOWNERS
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
Fix typo with passing params from RN to Android.
Fixes #400.
``` patch
diff --git a/dev-app/src/screens/CollectCardPaymentScreen.tsx b/dev-app/src/screens/CollectCardPaymentScreen.tsx
index 7ca6c9a..0a7a3a0 100644
--- a/dev-app/src/screens/CollectCardPaymentScreen.tsx
+++ b/dev-app/src/screens/CollectCardPaymentScreen.tsx
@@ -153,6 +153,7 @@ export default function CollectCardPaymentScreen() {
const response = await createPaymentIntent({
amount: Number(inputValues.amount),
currency: inputValues.currency,
+        customer: '<REDACTED>',
paymentMethodTypes: paymentMethods,
setupFutureUsage: enableInterac ? undefined : 'off_session',
onBehalfOf: inputValues.connectedAccountId,
```
Select one:
> [android] StripeTerminalReactNativeModule: Fix setting customer

- ios/Errors.swift
- ios/StripeTerminalReactNative.swift
Fixes https://github.com/stripe/stripe-terminal-react-native/issues/384
`createError` returns a dictionary with the "error" key already. So when an update failed we were unintentionally nesting that again and so we got error.error.[message|code].
https://github.com/stripe/stripe-terminal-react-native/issues/384
Tested by setting the update to fail for the simulated reader and confirmed the error isn't double nested:
| before | after |
| --- | --- |
|  `LOG  [Stripe terminal]: didFinishInstallingUpdate {"deviceSoftwareVersion": "2.01.00.08-SZZZ_US_v9-300001", "error": {"error": {"code": "ReaderSoftwareUpdateFailedBatteryLow", "message": "Updating the reader software failed because the reader's battery is too low. Charge the reader before trying again."}}, "estimatedUpdateTime": …
> [iOS] Fix double nesting of reader update error

- README.md
- bitrise.yml
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
- Bump XCode version used by bitrise to match the version we use internally
when building the iOS SDK.
- Update the podspec iOS version to 11, which is required as of iOS native SDK
version 2.14.0.
Fix CI and update iOS version.
Select one:
> Bump iOS versions

- bitrise.yml
- ios/Mappers.swift
Fixes https://github.com/stripe/stripe-terminal-react-native/issues/440
The iOS layer was missing a mapper from the ChargeStatus enum to a string. This adds that.
#440 
stepped through the mapper after a payment and also added a print out on the js side to see charges[0].status was set now.
Select one:
> Add missing mapper for iOS ChargeStatus enum

- ios/Mappers.swift
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/types/Reader.ts
- src/types/index.ts
This PR adds support for local mobile readers
We need this feature and it's already in stripe's roadmap. Full discussion here https://github.com/stripe/stripe-terminal-react-native/issues/439
To test I create a simple React Native app. I used `StripeTerminalProvider` and fetched a connection token from backend. Then just waited for Stripe Terminal to initialize, discovered all local mobile readers and connected to the first one. After connection I create a new payment intent, collect it and process it. I only got to the tap to pay screen, which I was not able to use because it asks me for a stripe test card to use in my test environment. So I guess there is still a small bit to test with processing and capturing the payment, but will only be able to do that later. My code looks something …
> Add local mobile support to iOS

- bitrise.yml
Attempt to fix build errors like:
> Could not configure Apple Service authentication: 2FA session saved
> in Bitrise Developer Connection is expired, was valid until 2023-03-12
> 21:32:16 +0000 UTC (exit code: 1)
https://app.bitrise.io/build/0565de0f-1eef-4d6c-a660-b6c5c709b6f4
> bitrise: Set apple dev connection to "off"

- ios/Mappers.swift
- src/types/Reader.ts
Add deviceType of reader for TTPOI.
When I wanted to use it to tell if my current connection was a TTPOI reader and skip connect, I found that there was no such deviceType. Just like the code below, so I want to add it.
```ts
if (connectedReader?.deviceType == 'appleBuiltIn') {
// do something
}
```
Select one:
> Add deviceType of reader for TTPOI.

- dev-app/package.json
- dev-app/src/api/api.ts
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/yarn.lock
passes along the `request_extended_authorization` and `request_incremental_authorization_support` params to the api call during PI create in the dev app.
update stripe dependency to `12.8.0` so we can get the updated types
unblocks some qa tests
tested on physical iphone and android
Select one:
> [dev app] pass on incremental/extended auth params and update stripe dependency

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- bitrise.yml
Due to Bitrise updates our builds have been failing and preventing us from merging PRs. This PR fixes the Bitrise build errors and also includes a user submitted bug fix [0] for Android initialization error.
[0] https://github.com/stripe/stripe-terminal-react-native/pull/463
https://github.com/stripe/stripe-terminal-react-native/issues/484
Bitrise failures
Select one:
> Add withExceptionResolver to Android Terminal init function

- android/build.gradle
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bump Android SDK to 2.21.1
Bump iOS SDK to 2.21.0
update native SDKs to 2.21.x
Select one:
> update native sdk

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/RefundPaymentScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Support refundApplicationFee and reverseTransfer options in in-person refunds.
For in-person refunds the dev app is missing the refundApplicationFee and reverseTransfer options.
Select one:
> Support  refundApplicationFee and reverseTransfer options in in-person refunds

- .gitignore
- fastlane/.env.default.example
For Apple dev account authentication for Fastlane deployers should set Apple ID and app-specific password in the env.default file. Adds an example and ignores the actual file
RN deploy improvements
Select one:
> Example env file for fastlane auth

- dev-app/src/Root.tsx
- example-app/src/Root.tsx
Prevent instantiating a new fetchTokenProvider function on each render pass.
Prevents the dev/example apps from reinitializing the Terminal SDK
more than once when unnecessary.
Select one:
> Cache token provider callback between re-renders.

- dev-app/src/screens/DiscoverReadersScreen.tsx
- Modify style of  Scrollview to make it adapt its height based on the size of its sub-container to display the content correctly.
- Users cannot scroll down the readers list in the  app in order to find and connect to an already registered reader if the list is larger than the screen displayed.
Select one:
> Fix discovery-readers cannot scroll down registered devices list.

- bitrise.yml
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bumps native SDKs to latest version
Fixes a regression in 2.21.0
Select one:
> Bump iOS SDK to 2.23.1

- android/build.gradle
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/ios/Podfile.lock
- dev-app/src/App.tsx
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/HomeScreen.tsx
- dev-app/src/screens/RefundPaymentScreen.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
- e2e/app.e2e.js
- e2e/internet-reader.e2e.js
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
bump native SDKs to 3.1.0.
add user cancellation for internet readers.
Select one:
> bump native SDKs to 3.1

- README.md
Notes issues with targetSdk 34
34 issue
Select one:
> Update README for 34 clarification

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/listener/RNOfflineListener.kt
- dev-app/src/screens/DatabaseScreen.tsx
- dev-app/src/screens/HomeScreen.tsx
- ios/Errors.swift
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/components/StripeTerminalProvider.tsx
- src/functions.ts
- src/hooks/useStripeTerminal.tsx
- src/types/index.ts
Fixes offlineStatus reporting by the SDK. Both `onDidChangeOfflineStatus` and `getOfflineStatus` should report the full `offlineStatus` object for reader and sdk.
Updates Android and iOS to return errors only when they exists, and updates dev-app to handle undefined error
Select one:
> Fix offline status 

- CONTRIBUTING.md
`CONTRIBUTING.md` had multiple references to this repo's example project. In `CONTRIBUTING.md`, the example project was supposed to belong in the `/example` directory, when it was actually in the `/example-app` directory. The `/example` directory does not exist. 
This is a tiny correction, but it adds a bit of unnecessary friction to the onboarding process :) 
N/A - all changes were made to docs. None of the functionality was changed. 
Select one:
> Added correct example app name

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/TerminalApplicationDelegate.kt
- dev-app/android/app/src/main/java/com/dev/app/stripeterminalreactnative/MainApplication.java
Adds AoD support for RN SDK. Users will need to modify their `MainApplication.java` file to call `onCreate`, other options we tested didn't register the callbacks fast enough on S700.
Feature parity! 
Select one:
> AoD support

- .github/ISSUE_TEMPLATE/bug_report.md
- android/build.gradle
- dev-app/ios/Podfile.lock
- package.json
Updates version to beta.15. Also fixes how Android integrations pick up the RN SDK version.
Release prep
Select one:
> Update RN SDK version to beta.15

- example-app/app.json
- src/plugin/withStripeTerminal.ts
Allow customisation of the pop-up message that appears when an Expo-based app attempts to connect to an Internet card reader for the first time, on iOS.
On iOS 14+, the first time that the app attempts to connect to an Internet card reader (such as the WisePOS), a message appears asking the user to allow access to the Local Network. The description that appears can be customised by setting the [`NSLocalNetworkUsageDescription` property list key](https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription). This change allows the description to be customised in an Expo app by setting the `localNetworkUsagePermission` property in the relevant plugin config.
Select one:
If/when this is merged and released, this will require changes to …
> feat: allow customization of Local Network message for Expo projects on iOS

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/AppContext.ts
- dev-app/src/Root.tsx
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/RefundPaymentScreen.tsx
- dev-app/src/types.ts
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Support Interac Refund.
Support Interac Refund.
Select one:
> Support Interac Refund

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/components/ListItem.tsx
- dev-app/src/screens/HomeScreen.tsx
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/__tests__/functions.test.ts
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/__tests__/useStripeTerminal.test.tsx
- src/hooks/useStripeTerminal.tsx
- src/types/index.ts
Add rebootReader method.
Support rebootReader SDK method.
Select one:
> Add rebootReader method

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/ReactNativeConstants.kt
- android/src/main/java/com/stripeterminalreactnative/listener/RNBluetoothReaderListener.kt
- android/src/main/java/com/stripeterminalreactnative/listener/RNUsbReaderListener.kt
- dev-app/src/screens/HomeScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/components/StripeTerminalProvider.tsx
- src/hooks/useStripeTerminal.tsx
- src/types/Reader.ts
- src/types/index.ts
Support reader disconnect reason
Support new reader disconnected callback and disconnect reason enum.
Select one:
> Support reader disconnect reason

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
Fixes https://github.com/stripe/stripe-terminal-react-native/issues/635
- [✅ ] I tested this manually
- [ ❌ ] I added automated tests
Select one:
- [❌ ] I have added relevant documentation for my changes.
- [✅ ] This PR does not result in any developer-facing changes.
> Adds addListener and removeListeners react methods to android module

- dev-app/ios/Podfile
- dev-app/ios/Podfile.lock
- dev-app/ios/StripeTerminalReactNativeDevApp.xcodeproj/project.pbxproj
- example-app/ios/Podfile
I woke up this morning to a freshly upgraded Xcode, version 15.3 of which broke Flipper and prevented RN apps in this repo from building. In [this upstream issue][0] the [official recommendation is simply to turn off Flipper][1] because it's deprecated.
[0]: https://github.com/facebook/react-native/issues/43335
[1]: https://github.com/facebook/react-native/issues/43335#issuecomment-1980788427
Select one:
> Disable Flipper in dev-app and example-app

- android/build.gradle
- dev-app/ios/Podfile.lock
- dev-app/ios/StripeTerminalReactNativeDevApp.xcodeproj/project.pbxproj
- stripe-terminal-react-native.podspec
Bump sdk to 3.4.0
Upgrade native SDKs to 3.4.0 
Select one:
> Bump sdk to 3.4.0

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/ktx/TerminalExtensions.kt
- dev-app/src/screens/DiscoverReadersScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Adds support for TTP auto-reconnection
3.4.0 update
Select one:
> Add TTP auto-reconnect support

- src/__tests__/__snapshots__/index.test.tsx.snap
- src/types/index.ts
Removes unused toggle type
clean up
Select one:
> Remove toggle type

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- dev-app/src/App.tsx
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/DatabaseScreen.tsx
- dev-app/src/screens/HomeScreen.tsx
- ios/Mappers.swift
- src/hooks/useStripeTerminal.tsx
- src/types/PaymentIntent.ts
- src/types/Reader.ts
- src/types/index.ts
Adds offline mode support for sPOS readers:
- Updates dev-app to create PIs client-side for sPOS readers 
- Adds offlineDetails to native mappers
Select one:
> sPOS offline mode support

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- dev-app/android/build.gradle
- example-app/android/build.gradle
- ios/Mappers.swift
- src/types/PaymentIntent.ts
Adds metadata field when returning PI 
Add missing fields
Select one:
> Add metadata field to payment intent

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/DiscoverReadersScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Add timeout param for BT discovery scan.
To support setting bluetooth discovery scan timeout.
Select one:
> Timeout for BT discovery scan

- dev-app/src/AppContext.ts
- dev-app/src/Root.tsx
- dev-app/src/screens/LocationListScreen.tsx
- dev-app/src/types.ts
- To support offline pairing of unseen readers, we need to cache the location list so that the user can select a location while offline. (technically we can also allow the user to manually input the location id, but this is easier to use)
Flow:
1. user pairs a bluetooth reader online (with location A)
2. user disconnects
3. user goes offline
4. user pairs a different bluetooth reader that has never been paired before to the app (of the same model) with the same location (location A)
5. reader is successfully paired
Allow testing for unseen readers offline
Select one:
> [TERMINAL] Cache locations for offline mode pairing

- dev-app/src/screens/DiscoverReadersScreen.tsx
Support Invalid location registration for mPOS readers.
Select one:
> Support Invalid location registration for mPOS readers.

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/Mappers.swift
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
- src/types/Reader.ts
Add method of supportsReadersOfType
Select one:
> Add method of supportsReadersOfType

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- ios/Mappers.swift
Our current paymentMethod mapper maps the `paymentMethod.card` field instead of `paymentMethod.cardPresent`. This PR adds support for mapping card and interac present
https://github.com/stripe/stripe-terminal-react-native/issues/697
Select one:
> Fix PaymentMethod mapping 

- ios/StripeTerminalReactNative.swift
For iOS reset all cancelables after confirm calls succeed.
Currently we set cancelables to nil after collect confirms, which causes issues when trying to inspect PM and decline payments between collect and confirm.
Select one:
> Nullify collect cancelables after confirm

- dev-app/src/AppContext.ts
- dev-app/src/Root.tsx
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/RefundPaymentScreen.tsx
- dev-app/src/types.ts
Fixed issue where  amount in full refund did not match the last payment on the React Native dev-app
Make sure app can detect the correct charge ID and last payment amount , so that user no need to input manually.
Select one:
> Fixed the amount mismatch in full refund

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
Support getting payment status
Add getters for missing values of Terminal.
Select one:
> Support getting payment status

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- bitrise.yml
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
- src/types/index.ts
Support getting ConnectionStatus from Terminal.
Add missing value ConnectionStatus to terminal.
Select one:
> Support getting ConnectionStatus value from Terminal

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
Support getting connectedReader from Terminal
Add getters for missing values of Terminal.
Select one:
> Support getting connectedReader from Terminal

- dev-app/src/screens/HomeScreen.tsx
s/disconneted/disconnected
[https://jira.corp.stripe.com/browse/RUN_TERMINAL_SDK-820](https://jira.corp.stripe.com/browse/RUN_TERMINAL_SDK-820) [mPOS][RN] Bluetooth reconnection popup misspelled 'disconnect'
Select one:
> Minor typo when reader is disconnected caught during QA

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Adjust ‘offlineBehavior’ type to be optional and improve ‘paymentMethodTypes’ handling to align with default behavior
Make `offlineBehavior` optional and update `paymentMethodTypes` handling to omit rather than set to null, ensuring default card_present PaymentIntent creation by the native SDK.
Select one:
> CreatePaymentIntent improvements

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
Fix incorrect unix time conversion at Android layer.
User reported that The availableUpdate object on the connectedReader object returned by the hook useStripeTerminal is inconsistent between android and iOS (The android's requiredAt is 1000 times bigger than it should be). This PR aims to correct this discrepancy to ensure cross-platform functionality is consistent and accurate.
https://github.com/stripe/stripe-terminal-react-native/issues/718
Select one:
> Fix incorrect unix time conversion at android layer

- ios/StripeTerminalReactNative.swift
We changed the parameter name from collectInputs and inputs in https://github.com/stripe/stripe-terminal-react-native/pull/721 but forgot to change the required param check in the native bridge.
Bug fix
Select one:
> Fix required param name for collectInputs

- dev-app/src/App.tsx
- dev-app/src/AppContext.ts
- dev-app/src/Root.tsx
- dev-app/src/api/api.ts
- dev-app/src/screens/MerchantSelectScreen.tsx
- dev-app/src/types.ts
Fixed a caching issue in the RN dev app that led to the Stripe-Account header not being cleared between direct and destination charge attempts.
To ensure API calls are successful when switching between charge types, without the interference of erroneously cached account information.
Select one:
> Fix dev-app cache Stripe-Account header-issue

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/functions.ts
- src/hooks/useStripeTerminal.tsx
- src/types/index.ts
Addresses discrepancy in the input shape of the `confirm` methods compared to other PI calls. The `confirm` method currently does not use a params object, unlike the other PI calls.
Align the input parameters of the "confirm" methods with the input shapes of other PI calls to ensure consistency in API calls.
Select one:
> ConfirmPaymentIntent methods accept param objects

- src/plugin/withStripeTerminal.ts
Modify expo config ti disable jetifier for jackson-core by default.
To improve issue [https://github.com/stripe/stripe-terminal-react-native/issues/653](https://github.com/stripe/stripe-terminal-react-native/issues/653)
new gradle properties setup after improvement.
Select one:
> Disable jetifier for jackson-core by default

- android/build.gradle
- dev-app/ios/Podfile.lock
- e2e/in-person-refund.e2e.js
- stripe-terminal-react-native.podspec
Bump sdk to 3.7.0
Upgrade terminal SDKs.
Select one:
> Bump sdk to 3.7.0

- scripts/publish.sh
Publish script changes to force devs into typing the branch name when releasing and disables releases from the main branch to promote using release branches
KTLO
Select one:
> Modify script to allow release from non-main branch

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectInputsScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
Fix issue with CollectInputs return values on iOS.
To fix issue [https://github.com/stripe/stripe-terminal-react-native/issues/743](https://github.com/stripe/stripe-terminal-react-native/issues/743)
after
Select one:
> Fix issue with CollectInputs return values on iOS

- bitrise.yml
- dev-app/ios/Podfile
- dev-app/ios/Podfile.lock
- dev-app/ios/StripeTerminalReactNativeDevApp.xcodeproj/project.pbxproj
- dev-app/ios/StripeTerminalReactNativeDevApp.xcodeproj/xcshareddata/xcschemes/UnitTests.xcscheme
- ios/Tests/MappersTests.swift
- stripe-terminal-react-native.podspec
Followed along with how stripe-react-native has things setup.
- The .podspec specifies the tests and excludes them from the main sources
- The Podfile sets up a test target
- Create a new UnitTests scheme in the xcworkspace that builds and tests from the new target
- import the stripe_terminal_react_native as a `@testable import...` so the classes are exposed
- write tests
I wrote a very simple, not very useful, test on the location status mapper as an example.
tests!
CI
Select one:
> Wire up ability to write iOS unit tests

- bitrise.yml
- ios/Protocols.swift
- ios/Tests/MappersTests.swift
- package.json
Add unit test on iOS for function automated testing.
Add automated testing requested by [https://bugs.bbpos.com/projects/SDK/issues/SDK-174](https://bugs.bbpos.com/projects/SDK/issues/SDK-174)
Select one:
> Add unit test on iOS

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Add missing  locationId parameter in discoverReaders method .
Support the discoverReaders method to accept locationId so that users can filter readers by it when using the Interent model
Select one:
> Add missing  locationId parameter in discoverReaders method 

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/callback/RNCollectedDataCallback.kt
- dev-app/src/App.tsx
- dev-app/src/screens/CollectDataScreen.tsx
- dev-app/src/screens/HomeScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/__tests__/__snapshots__/index.test.tsx.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
- src/types/index.ts
Add collectData feature in sdk
Support new collectData feature
Select one:
> Support CollectData feature

- dev-app/src/screens/DiscoverReadersScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/hooks/useStripeTerminal.tsx
- src/types/index.ts
Add callback event when user accept the terms of service of using tap to play on iOS side.
Part of the request from https://bugs.bbpos.com/projects/SDK/issues/SDK-189
iOS ref: https://stripe.dev/stripe-terminal-ios/docs/Protocols/SCPLocalMobileReaderDelegate.html#/c:objc(pl)SCPLocalMobileReaderDelegate(im)localMobileReaderDidAcceptTermsOfService:
Select one:
> Integrate ios local mobile terms of service accept callback

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
Fix getLocation api param limit wrong value
As describe in https://bugs.bbpos.com/browse/SDK-223
The limit key is accidentally assign wrong value
Select one:
> Fix getLocation api param limit wrong value

- dev-app/src/screens/LocationListScreen.tsx
Fix infinite loop location api
Using `useEffect` with multiple dependency might cause infinite loop as here. 
And also js is using `Object.is` to compare diff instead of the real content, so sometime what we think is the same isn't.
The solution is to break single `useEffect` into two for now to avoid nested update trigger loop.
Reference: https://bugs.bbpos.com/browse/SDK-219
Select one:
> Fix infinite loop location api

- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
https://bugs.bbpos.com/browse/SDK-218
Bump iOS SDK version to 3.8.3
Upgrade the native iOS SDKs to the latest.
Testing via apply change in https://github.com/stripe/stripe-terminal-react-native/pull/790
Select one:
> Bump ios sdk version to 3.8.3

- README.md
Update withStripeTerminal variable reference link
The line number in source code file is shifted since the code is rapidly evolved, update and also point to a range instead of single line for now.
The original reference should be: https://github.com/stripe/stripe-terminal-react-native/blame/a534b8f8efb42ec033c278c4058bcf8755d2abf2/src/hooks/useStripeTerminal.tsx#L51
Select one:
> Update withStripeTerminal variable reference link

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/TokenProvider.kt
- android/src/test/java/com/stripeterminalreactnative/TokenProviderTest.kt
- ios/StripeTerminalReactNative.swift
- ios/TokenProvider.swift
- src/components/StripeTerminalProvider.tsx
- src/functions.ts
- src/types/index.ts
fix connection issues with beta.20, improve the method of fetching and setting token.
To fix the issues reported by users that connecting device would timeout on the first running after app installed.
Select one:
> fix connection issue

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
Add `getNativeSdkVersion` to get native sdk version
Add `getNativeSdkVersion` function to reveal the embedded Android/iOS sdk version.
Reference: https://bugs.bbpos.com/browse/SDK-227
Select one:
> Add `getNativeSdkVersion` to get native sdk version

- src/__tests__/__snapshots__/index.test.tsx.snap
- src/index.tsx
Expose RN SDK version
We should expose RN SDK version so user will have a better way to check which version they integrate.
https://bugs.bbpos.com/browse/SDK-228
Select one:
> Expose RN SDK version

- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bump iOS SDK version to 3.9.1
https://jira.corp.stripe.com/browse/TERMINAL-40279
Upgrade the native iOS SDKs to the latest.
Select one:
> Bump ios sdk to 3.9.0

- dev-app/src/App.tsx
- dev-app/src/components/List.tsx
- dev-app/src/screens/DiscoverReadersScreen.tsx
- dev-app/src/screens/HomeScreen.tsx
Add timeout in discover reader in dev-app
Add timeout in discover reader for testing purpose
https://jira.corp.stripe.com/browse/TERMINAL-40545
Select one:
> Add timeout in discover reader in dev-app

- src/components/StripeTerminalProvider.tsx
Add ACCEPT_TERMS_OF_SERVICE event in StripeTerminalProvider
To align existing design, we'll add ACCEPT_TERMS_OF_SERVICE to StripeTerminalProvider as well.
Select one:
> Add ACCEPT_TERMS_OF_SERVICE event in StripeTerminalProvider

- dev-app/src/screens/DiscoverReadersScreen.tsx
By pass user cancel error in DiscoverReaderScreen page
https://jira.corp.stripe.com/browse/TERMINAL-40457
User cancel event in discover reader page shouldn't treat as error and it didn't provide value in testing. So we decided to by pass it instead.
Select one:
> By pass user cancel error in DiscoverReaderScreen page

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/callback/RNCollectInputResultCallback.kt
- ios/Mappers.swift
- ios/Tests/MappersTests.swift
- src/types/index.ts
Update collect input to use FormType variable instead of each tag like: text, phone, etc.
https://jira.corp.stripe.com/browse/TERMINAL-40991
Select one:
> Update collect input to use FormType variable

- dev-app/src/screens/DiscoverReadersScreen.tsx
Add each cancel error code for each platform
Part of https://github.com/stripe/stripe-terminal-react-native/pull/831 work.
Since the error code is not sync in Android/iOS, we have to handle separately.
Select one:
> Add ios error code to skip display error when discovering

- dev-app/Gemfile
- dev-app/src/screens/DiscoverReadersScreen.tsx
Enable toggle for local mobile discovery method
iOS support reconnect for local mobile discovery method, so we should enable this toggle in RN dev-app for testing.
Select one:
> Enable toggle for local mobile discovery method

- bitrise.yml
Update to M2 builders.
M1 builders are deprecated.
CI
> Update to M2 CI

- src/functions.ts
Fix `Terminal.collectData` to return the collected data in the correct `CollectDataResultType` format. The previous solution was directly returning the collected data object, when it should be returning it nested inside a `collectedData` key as defined in `CollectDataResultType`.
cc-ing @EricLin-BBpos who worked on the initial PR: #765 
Internal ticket filed by QA: https://jira.corp.stripe.com/browse/TERMINAL-41707
Tested manually with the dev-app. Ran `npx react-native run-ios --device`
Select one:
> Update collectData response to return as a CollectDataResultType

- dev-app/src/screens/CollectCardPaymentScreen.tsx
Sync interac_present info in CollectCardPaymentScreen in dev-app.
https://jira.corp.stripe.com/browse/TERMINAL-41708
There's two elements affect the present of `interac_present`, now we sync all of this controls and also only leverage on react native's setState method in order to fix un-sync issue.
Select one:
> Sync interac_present info in CollectCardPaymentScreen in dev-app.

- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/StripeTerminalReactNative.swift
We were passing an empty string to collectPaymentIntent for `surchargeNotice` which is causing the SDK to think we are trying to set it every time. This PR fixes the dev-app so we don't pass a value if it's `false` by JS standards. It also removed the `updatePaymentIntent` check to set `surchageNotice` as that's handled by the native SDK and we should just pass whatever we received from the user blindly.
Select one:
> Fix surcharge param passing in dev-app and iOS bridge

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
Fix tap to pay ux config hanging issue
https://github.com/stripe/stripe-terminal-react-native/issues/861
Select one:
> Fix tap to pay ux config hanging issue

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
- Add support for Affirm PaymentMethodType
- Add support for passing return_url in ConfirmConfiguration
- Update iOS pods for hermes engine
Select one:
> [4.1.0] Add support for return_url and Affirm

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/test/java/com/stripeterminalreactnative/MapperTest.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- ios/Tests/MappersTests.swift
- src/types/index.ts
Support moto parameter
https://jira.corp.stripe.com/browse/TERMINAL-41667
Select one:
> Support moto parameter

- android/build.gradle
- ios/StripeTerminalReactNative.swift
- src/functions.ts
Fix RN implementations of CollectedDataCallbacks. #849 unfortunately only fixed an issue on iOS, and it turns out the Android implementation was already correctly wrapping collectData in the proper `{ collectedData: <object> }`. This PR fixes the iOS implementation and undoes #849 
Also bumped gradle to 8.7.2 because I was running into cmake issues locally when building. I can revert if people have FUD
Jira ticket from QA: https://jira.corp.stripe.com/browse/TERMINAL-44410
Tested manually on iOS + Android using `npx react-native run-ios` `npx react-native run-android` 
Select one:
> Make collectData callbacks uniform; bump gradle to 8.7.2

- dev-app/src/App.tsx
- dev-app/src/screens/HomeScreen.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
Follow the flow in CollectCardPaymentScreen to change createSetupIntent check from checking `discoveryMethod == internet` to `deviceType == verifoneP400`. In order to make general internet connection can use the moto flow in dev-app.
https://jira.corp.stripe.com/browse/TERMINAL-44237 
Select one:
> [WIP] Change setupIntentScreen check condition

- dev-app/ios/Podfile.lock
- ios/StripeTerminalReactNative.swift
- stripe-terminal-react-native.podspec
Minimal change for iOS sdk 4.3.0
- iOS sdk 4.3.0
- Update: Added a new id parameter to collect input's SelectionButton to uniquely identify the button.
Note: js related change is done in https://github.com/stripe/stripe-terminal-react-native/pull/915/files
https://jira.corp.stripe.com/browse/TERMINAL-45162
Select one:
> Minimal change for iOS sdk 4.3.0

- android/build.gradle
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectInputsScreen.tsx
- src/types/index.ts
Minimal change for Android sdk 4.3.0
- Android sdk 4.3.0
- Update: Added a new id parameter to collect input's SelectionButton to uniquely identify the button.
https://jira.corp.stripe.com/browse/TERMINAL-45124
Select one:
> Minimal change for Android sdk 4.3.0

- src/hooks/useStripeTerminal.tsx
Interface refine for connectReader
https://jira.corp.stripe.com/browse/TERMINAL-44261
We'd like to clear communicate with user that `connectReader` can accept parameter like: `ConnectBluetoothReaderParams | ConnectUsbReaderParams | ConnectTapToPayParams | ConnectHandoffParams | ConnectInternetReaderParams`
Screenshot in VSCode:
Select one:
> Interface refine for connectReader

- bitrise.yml
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/HomeScreen.tsx
- dev-app/src/screens/UpdateReaderScreen.tsx
- maestro/app.yml
- maestro/e2e/checkIfConnected.yaml
- maestro/e2e/collectPayment.yaml
- maestro/e2e/connectReader.yaml
- maestro/e2e/inpersonRefund.yaml
- maestro/e2e/setupIntent.yaml
- package.json
Extract maestro config APP_ID and use Id for matching
- Extract APP_ID for future iOS support
- Use Id for matching
Select one:
> Extract maestro config APP_ID and use Id for matching

- bitrise.yml
- package.json
Update ios e2e test using maestro
Since detox is not working in ci env for iOS and we've migrate Android side, we'd like to move to maestro step by step on iOS as well.
Currently it support local test on simulator iPhone16 with simulate config is on and pre-set the merchant info.
Can trigger using `yarn e2e:test:ios:release` at root folder to verify/test.
Select one:
> Update ios e2e test using maestro

- android/build.gradle
- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/ReactNativeConstants.kt
Bump the Android native SDK version to 4.4 and update the related code
We are working on the native SDKs 4.4 upgrade.
Because the Android native SDK has 1 exposing enum change, I want an independent PR for the bumping version of the Android native SDK.
- Extract the hardcode Device Strings to an `enum` for better style.
Select one:
> Bump Android native SDK to 4.4

- android/src/main/java/com/stripeterminalreactnative/Errors.kt
- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/NativeTypeFactory.kt
- android/src/main/java/com/stripeterminalreactnative/ReactExtensions.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/test/java/com/stripeterminalreactnative/MapperTest.kt
- dev-app/ios/Podfile.lock
- dev-app/src/screens/CollectInputsScreen.tsx
- ios/Errors.swift
- ios/Mappers.swift
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- ios/Tests/MappersTests.swift
- src/StripeTerminalSdk.tsx
- src/functions.ts
- src/hooks/useStripeTerminal.tsx
- stripe-terminal-react-native.podspec
Add simulated Internet reader support for collecting inputs on iOS side
We are upgrading the functionality of iOS SDK 4.4. This PR is a function of it.
**bugfix**: Add the missing timeout scenario to Android side.
1. Check the `simulated toggle button` and Discovery Method should be `internet`.
Then discover reader and choose one.
2. Click `collect payment`
3. We have three scenarios `["none", "all" "timeout"]`
1.  Successful input collection without skipping any inputs
2. Successful input collection with skipping all non-required inputs
3. Failed input collection because of a timeout
choose one and click `Phone,  email,  numeric, and text forms`
4. Check the result
Select one:
> Add simulated Internet reader support for collecting inputs on iOS side

- ios/StripeTerminalReactNative.swift
The `PaymentIntent` instance returned from the `collectPaymentMethod` is the updated API response instance. The native SDK expects that updated instance and currently won't pass through the confirmConfig values if that instance isn't the one passed in to the confirmRequest (being improved separately).
Fix bug where surcharge amount wasn't passed through to the confirm request
https://jira.corp.stripe.com/browse/TERMINAL-46232
manually confirmed amount surcharge is passed through to the reader and the API
Select one:
> Fix amount surcharge not being passed through to the reader confirm request

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- ios/Mappers.swift
- src/types/Reader.ts
We are updating the native SDKs to 4.4. And this PR is a new feature in the upgrade.
iOS
- Added new mobile reader disconnect reasons: bluetoothSignalLost, usbDisconnected, and idlePowerDown to [SCPDisconnectReason](https://stripe.dev/stripe-terminal-ios/docs/Enums/SCPDisconnectReason.html).
Android: 
- Improved visibility into mobile reader disconnects by exposing new disconnect reasons: [DisconnectReason.USB_DISCONNECTED](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-disconnect-reason/-u-s-b_-d-i-s-c-o-n-n-e-c-t-e-d/index.html), and [DisconnectReason.IDLE_POWER_DOWN](https://stripe.dev/stripe-terminal-android/external/com.stripe.stripeterminal.external.models/-disconnect-reason/-i-d-l-e_-p-o-w-e-r_-d-o-w-n/index.html).
Select one:
> Add new reader disconnect reasons from Android & iOS native SDK v4.4

- android/src/main/java/com/stripeterminalreactnative/TapToPay.kt
- dev-app/android/app/src/main/java/com/dev/app/stripeterminalreactnative/MainApplication.kt
Tap to Pay operates within a dedicated process, a second instance of your application, to ensure the secure handling of payment data. As a result, the client app's Application subclass will also be initialized within this process. Given that certain operations in the application class may be incompatible in this process, checking if the device is processing Tap To Pay can be utilized to determine whether the application should skip those operations at all.
Android native SDK 4.4 has this new checking, so we want to have it in the React Native SDK, too.
Select one:
> Add TapToPay processing check to the Android module

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- src/types/PaymentIntent.ts
Add a new filed `clientSecret` to Payment Intent.
Stripe provides client_secret in payment intent, which was created by Android native SDK. This PR is to eliminate the gap between RN and Android SDK. 
Select one:
> Expose client secret in payment intent on Android side

- dev-app/src/components/AlertDialog.tsx
- dev-app/src/screens/HomeScreen.tsx
Fix the display logic of disconnect dialog in dev-app
The disconnect dialog might not pop up in some scenarios. Hence, we want to review and optimize the mechanism of it.
Root cause: when the app receives a disconnect in the background, the dialog will pop up on the “connected screen”, but the component used is the default Alert dialog, which may be ignored by the os when the app is in the background. And after disconnecting, we will go back to “unconnected screen” from “connected screen”, they are different layout.
Solution: Use a custom component and record the state, put the alert dialog in the root of HomeScreen.
New logic: The dialog will be shown every time the reader disconnects. The dialog will not be displayed only when the User triggers a disconnection.
Select one:
> Fix the display logic of disconnect dialog in dev-app

- android/gradle.properties
In React Native SDK, we will use Android native SDK 4.5.1 and ignore the Android native SDK 4.5.0.
We are aware of some issues in Android native SDK 4.5.0, hence we will use 4.5.1 for the next React Native release.
Select one:
> Bump Android native SDK version to 4.5.1

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
Fix named argument issue for Promise usage in Android
https://jira.corp.stripe.com/browse/TERMINAL-48539
Promise change from Java to Kotlin in 2024/08, and named argument is not support in Java. So we need to remove that in SDK to avoid build fail for user using old react native SDK like 0.74 or any old version before the migration.
Ref: https://github.com/facebook/react-native/pull/44587
Select one:
> Fix named argument issue for Promise usage in Android

- android/gradle.properties
- dev-app/ios/Podfile.lock
- ios/StripeTerminalReactNative.swift
- stripe-terminal-react-native.podspec
- Bump Android/iOS SDKs to version 4.6.0
- **Changelogs**:
- [Android](https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#460---2025-08-01)
- [iOS](https://github.com/stripe/stripe-terminal-ios/blob/master/CHANGELOG.md#460-2025-08-04)
Bringing in new SDK changes for printing support
Ensure CI passes
Select one:
> Bump iOS/Android SDKs to 4.6.0

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectDataScreen.tsx
- ios/StripeTerminalReactNative.m
- ios/StripeTerminalReactNative.swift
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
Add the `cancelCollectData` function to the SDK interface. If a user starts a collectData operation and wants to cancel it, they can use this new function.
We found an issue during the regression: we can't cancel the collectData operation. Hence, this PR is for adding the `cancelCollectData` function.
We also update the dev-app to show the `cancelCollectData` function.
Select one:
> Add the CancelCollectData function to the SDK interface

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/ReactNativeConstants.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
To support the new Surcharge Configuration exposed by Android SDK 4.5.0 and iOS SDK 4.6.0. We need to update the React Native SDK.
Android SDK release note: https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md#450---2025-06-10 
iOS SDK release note: https://github.com/stripe/stripe-terminal-ios/releases/tag/4.6.0 
We add a new consent field to get users' consent related to the surcharge fee.
For the new Surcharge Configuration
**There is one last step left, verify consent.**
Select one:
**Need to update the document**
> Update Surcharge operation to support new configuration

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- example-app/src/api/api.ts
- ios/Mappers.swift
- src/types/index.ts
Add support PayNow for ReactNative SDK and fix capture_method in example-app
JIRA ticket: https://jira.corp.stripe.com/browse/TERMINAL-47265
Tested paymenIntent for IOS: pi_3RxxjJFBrCETb2z91r4ciEwD
Tested paymenIntent for Android: pi_3RxxAyFBrCETb2z92hdSNYx1
Select one:
> [Paynow][Terminal]Add support forPaynow and fix capture_method in example-app

- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/RefundPaymentScreen.tsx
- dev-app/src/util/currencyUtils.ts
- example-app/src/screens/CollectCardPaymentScreen.tsx
- example-app/src/screens/RefundPaymentScreen.tsx
- example-app/src/util/currencyUtils.ts
cc @uintaam
Added JPY currency support and implemented zero-decimal currency handling in both example-app and dev-app. Zero-decimal currencies (JPY, KRW, etc.) now display amounts correctly without dividing by 100, while regular currencies continue to work as before.
JPY was missing from the supported currencies list in the demo applications. Additionally, the existing amount formatting logic incorrectly divided all amounts by 100, which is incorrect for zero-decimal currencies like JPY where amounts are already in the base currency unit (¥100 should display as "100", not "1.00").
This change ensures proper currency support and display formatting for international users, particularly those using Japanese Yen and other zero-decimal currencies.
> Add JPY currency support and zero-decimal currency handling

- dev-app/src/screens/HomeScreen.tsx
- AlertDialog caused complete UI freeze when navigating from CollectPaymentScreen → HomeScreen (**iOS only**).   
Modal's event handling mechanism broke due to timing mismatch:   
1. Wrong Timing: onDidSucceedReaderReconnect callback triggered during navigation
2. State Update: setShowReconnectSuccessAlert(true) called before HomeScreen fully ready
3. Broken Modal: Modal rendered but event listeners not properly bound
4. Event Black Hole: Modal intercepted all touch events but couldn't respond
5. UI Freeze: Entire interface became unresponsive
I am not sure how to avoid it by using State and AlertDialog, hence i replaced AlertDialog with native Alert.alert():
1. Bypasses React Modal system entirely
2. No dependency on component lifecycle timing
3. Platform-native event handling
In our …
> Fix the issue that reconnected alert freezes the HomeScreen

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/main/java/com/stripeterminalreactnative/TokenProvider.kt
- android/src/test/java/com/stripeterminalreactnative/TokenProviderTest.kt
- ios/StripeTerminalReactNative.swift
- ios/Tests/TokenProviderTests.swift
- ios/ThreadSafeQueue.swift
- ios/TokenProvider.swift
- src/components/StripeTerminalProvider.tsx
- src/functions.ts
- src/types/index.ts
Change token callback usage and functionality
This is an improvement of https://github.com/stripe/stripe-terminal-react-native/pull/791 where we want to get rid of `setConnectionToken requires the callbackId to be set to the callbackId value provided to the tokenProviderHandler.` error been throw which related to https://github.com/stripe/stripe-terminal-react-native/issues/979
The existing token flow will act like:
1. TokenProvider.fetchConnectionToken request been called in Android with the callback function as variable
1. Create a key-value pair store into callbackMap with a random callbackId as key in TokenProvider for later use
1. Send FETCH_TOKEN_PROVIDER event from Android to RN with callbackId
1. Receive FETCH_TOKEN_PROVIDER notification in RN and fetchToken in RN layer
1. Send …
> Change token callback usage and functionality

- android/src/test/java/com/stripeterminalreactnative/FeatureParityTest.kt
- maestro/e2e/setupIntent.yaml
Add basic test for feature parity
https://jira.corp.stripe.com/browse/TERMINAL-48587
Since Android/iOS feature is mostly in sync, we can test on Android side to see if every native SDK function has a corresponding RN function to ensure we don't miss any integration in long term.
Select one:
> Add basic test for feature parity
