- CODEOWNERS
> removing james as codeowner

- android/build.gradle
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
What is says on the tin, backend issues have been resolved, upgrade is green now.
KTLO
CI passes, 🚢 
Select one:
> bumping android to 2.12.0

- package.json
> package.json: Revert mistaken version patch bump

- dev-app/ios/Podfile.lock
- example-app/ios/Podfile.lock
- example-app/package.json
- example-app/yarn.lock
Ran:
```
old_version=0.0.1-beta.9; new_version=0.0.1-beta.10; git grep -G -l "$old_version" -- ':!**/yarn.lock' | xargs gsed -i "s/$old_version/$new_version/g" && cd dev-app/ios && pod install && cd - && cd example-app/ios && pod install && cd - && cd example-app && yarn && cd -
```
> apps: Update to latest release (0.0.1-beta.10)

- scripts/publish.sh
> scripts/publish: Fix handling of zero arguments

- .detoxrc.json
- dev-app/ios/Podfile.lock
- example-app/ios/Podfile.lock
- example-app/package.json
- example-app/yarn.lock
Update our apps to use the latest release.
> Update apps to latest release (v0.0.1-beta.11)

- bitrise.yml
Set up Bitrise. I *think* I captured everything in the CircleCI build, but I'm not very familiar with this project. Please take a look!
Replacing CircleCI.
Bitrise CI.
Select one:
> Set up Bitrise

- .github/ISSUE_TEMPLATE/bug_report.md
- dev-app/ios/Podfile.lock
- example-app/ios/Podfile.lock
- example-app/package.json
- example-app/src/screens/HomeScreen.tsx
- example-app/yarn.lock
Post release updates
Select one:
> Update RN SDK version for apps to beta.12

- dev-app/src/App.tsx
- dev-app/src/screens/LocationListScreen.tsx
- dev-app/src/screens/RegisterInternetReaderScreen.tsx
add dummy locations list for invalid location registration test.
add test case of registering a reader with an invalid location.
Select one:
> add dummy locations for invalid location registration test.

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/api/api.ts
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Add routing priority picker.
Add routing priority field in createPaymentIntent method.
To set the requested priority field when creating a PaymentIntent.
Select one:
> routing priority

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
- Support updatePaymentIntent parameter in CollectConfiguration.
- Support updatePaymentIntent parameter in CollectConfiguration for collectPaymentMethod method.
Select one:
> Support updatePaymentIntent parameter

- android/build.gradle
Bumps Terminal Android SDK version to 2.23.1
Latest and greatest 
Select one:
> Bump android to 2.23.1

- dev-app/package.json
- example-app/package.json
Prepends `@stripe` prefix to package names
Clarity
Select one:
> Improve package names

- scripts/publish.sh
Updates repo name in comments to terminal RN
Clean up
Select one:
> FIx repo name

- android/build.gradle
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
> Bump SDKs to 3.2.1

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/Mappers.swift
- src/types/PaymentIntent.ts
- src/types/index.ts
Support showing the CardPresentDetails of Charges on the log screen.
Propagate card present details up to users on the react-native integration.
Select one:
> Support Card Present Details

- .detoxrc.json
- Brewfile
- bitrise.yml
- dev-app/ios/StripeTerminalReactNativeDevApp.xcodeproj/project.pbxproj
Updates bitrise xcode instance to 15.
KTLO
CI
Select one:
> Upgrade xcode to 15

- ios/Mappers.swift
fix card present detail network issue
Select one:
> fix card present detail network issue

- package.json
- yarn.lock
Dependency to upgrade to fix Expo build failures.
Bug fix
`npx expo prebuild` runs successfully
Select one:
> Upgrade config-plugins

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- ios/Mappers.swift
- src/types/PaymentIntent.ts
Add missing fields to PI object.
Select one:
> Add missing fields to PI object

- android/build.gradle
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bump to sdks 3.5.0
Upgrade terminal SDKs.
Select one:
> Bump to sdks 3.5.0

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- dev-app/src/screens/SetupIntentScreen.tsx
- ios/Mappers.swift
- src/types/Refund.ts
- src/types/SetupIntent.ts
Add missing fields for SetupIntent and Refund.
Add setupIntent&refund's missing fields.
Select one:
> Complete setupIntent&refund fields

- dev-app/src/screens/HomeScreen.tsx
- ios/StripeTerminalReactNative.m
- src/StripeTerminalSdk.tsx
- src/__tests__/__snapshots__/functions.test.ts.snap
- src/functions.ts
- src/hooks/__tests__/__snapshots__/useStripeTerminal.test.tsx.snap
- src/hooks/useStripeTerminal.tsx
Add reconnecting popup.
Add screen pops-up for auto-reconnection.
Select one:
> Add reconnecting popup

- .detoxrc.json
- bitrise.yml
Bump Android SDK target to 34
Select one:
> Bump SDK target to 34

- .github/ISSUE_TEMPLATE/bug_report.md
- dev-app/ios/Podfile.lock
- example-app/ios/Podfile.lock
- example-app/package.json
- example-app/yarn.lock
- package.json
> Upgrade SDK version to .18

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
- `requestDynamicCurrencyConversion` option is added to the `CollectConfigurationBuilder`
- Add support for Dynamic Currency Conversion on sPOS devices (beta)
Select one:
> Add support for dynamic currency conversion (beta)

- bitrise.yml
1.14.2 -> 1.15.2
Unblock CI
Select one:
> Upgrade cocoapods version

- android/build.gradle
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bump to sdks 3.6.0
Select one:
> Bump to sdks 3.6.0

- README.md
Fixed a typo in the PaymentScreen.tsx example of the README.md file.
Documentation correctness
Select one:
> Fix PaymentScreen.tsx example in README.md

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- e2e/app.e2e.js
- e2e/internet-reader.e2e.js
- e2e/utils.js
- ios/Errors.swift
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Add surcharging feature in  sdk
Support new surcharging feature
Select one:
> Support surcharging

- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
- e2e/app.e2e.js
- ios/Mappers.swift
Fix wrong display of the "terminal.didRequestReaderDisplayMessage"
Fix bug
Select one:
> Fix wrong display of the "terminal.didRequestReaderDisplayMessage"

- example-app/ios/Podfile.lock
- example-app/package.json
- example-app/src/screens/CollectCardPaymentScreen.tsx
- example-app/src/screens/SetupIntentScreen.tsx
- example-app/yarn.lock
Upgrade example-app to RN SDK beta.20
update example-app to use the latest version of RN SDK  beta.20
Select one:
> Upgrade example-app to RN SDK beta.20

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- ios/Mappers.swift
- src/types/index.ts
Add missing `type` field to PaymentMethod
Select one:
> Add type field to PaymentMethod mappers

- example-app/android/app/src/main/java/com/example/stripeterminalreactnative/MainApplication.kt
Add aod support to example-app
Update example-app to support App on Device.
Select one:
> add aod support to example-app

- dev-app/src/screens/HomeScreen.tsx
https://bugs.bbpos.com/browse/SDK-229
Add version info in home page
We should display the sdk version inside dev-app for better testing
Select one:
> Add version info in home page

- android/build.gradle
Upgrade Android SDK to latest
KTLO
Select one:
> Bump android to 3.9.1

- android/build.gradle
Bump android sdk to 3.9.2
https://jira.corp.stripe.com/browse/TERMINAL-40279 
Select one:
> Bump android sdk to 3.9.2

- .github/ISSUE_TEMPLATE/bug_report.md
- android/build.gradle
- dev-app/ios/Podfile.lock
- package.json
Upgrades version names for a couple places:
- Updates dev-app iOS pods
- Updates RN version name ahead of new release cut
- Updates Android SDK to latest
KTLO
- [ x I tested this manually
Select one:
> SDK version updates

- android/build.gradle
Bump android sdk to 3.9.5
Select one:
> Bump android sdk to 3.9.5

- dev-app/src/screens/LocationListScreen.tsx
Fix dev-app location page not scrollable issue
https://jira.corp.stripe.com/browse/TERMINAL-40665
The FlatList seems has issue on Android emulator, change to ScrollView with List structure and combine two scrollable View into one.
Select one:
> Fix dev-app location page not scrollable issue

- README.md
https://github.com/stripe/stripe-terminal-android/issues/387 is now resolved
Select one:
> Update README.md for Android requirements

- android/build.gradle
Bump android sdk to 3.10.0
https://jira.corp.stripe.com/browse/TERMINAL-41041
Select one:
> Bump android sdk to 3.10.0

- dev-app/android/build.gradle
Update target android sdk to 35
Select one:
> Update target android sdk to 35

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- bitrise.yml
- dev-app/Gemfile.lock
Our Pods instal was failing with: `You have requested: xcodeproj = 1.25.1 The bundle currently has xcodeproj locked at 1.25.0. Try running bundle update xcodeproj` causing issues for unit and e2e ios tests and unit-android test was complaining about syntax issues
This PR fixes the xcodeproj mismatch and Kotlin syntax errors
KTLO
Select one:
> Fix build issues

- ios/Mappers.swift
Fix tip parsing logic in iOS
https://github.com/stripe/stripe-terminal-react-native/issues/854
Select one:
> Fix tip parsing logic in iOS

- dev-app/ios/Podfile.lock
- dev-app/package.json
- dev-app/yarn.lock
- package.json
- yarn.lock
Fixes a bug with boost installation: https://github.com/facebook/react-native/releases/tag/v0.72.9
Select one:
> Upgrade RN to 72.9

- android/build.gradle
- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Bump SDK to 4.1.0
https://jira.corp.stripe.com/browse/TERMINAL-42364
Select one:
> Bump SDK to 4.1.0

- dev-app/src/screens/CollectCardPaymentScreen.tsx
- dev-app/src/screens/DatabaseScreen.tsx
- example-app/src/screens/CollectCardPaymentScreen.tsx
- example-app/src/screens/DatabaseScreen.tsx
Update the available currencies to all those supported on Terminal.
Allow for more realistic testing across geographies.
Select one:
> Update supported currencies

- README.md
> Update Readme min versions

- bitrise.yml
- dev-app/src/screens/DiscoverReadersScreen.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
- maestro/app.yml
- maestro/e2e/checkIfConnected.yaml
- maestro/e2e/collectPayment.yaml
- maestro/e2e/connectReader.yaml
- maestro/e2e/inpersonRefund.yaml
- maestro/e2e/setupIntent.yaml
- package.json
Fix Android e2e test by leverage on Maestro
https://jira.corp.stripe.com/browse/TERMINAL-44261
Select one:
> Fix Android e2e test by migrate to Maestro

- CODEOWNERS
Just adding sjl to the CODEOWNERS list
> [easy] Update CODEOWNERS

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- ios/Mappers.swift
Add cardDetail in PaymentMethodDetails
https://jira.corp.stripe.com/browse/TERMINAL-45166
Select one:
> Add cardDetail in PaymentMethodDetails

- android/src/main/java/com/stripeterminalreactnative/Mappers.kt
- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- android/src/test/java/com/stripeterminalreactnative/MapperTest.kt
- dev-app/src/screens/CollectCardPaymentScreen.tsx
- ios/Mappers.swift
- ios/StripeTerminalReactNative.swift
- ios/Tests/MappersTests.swift
- src/types/index.ts
Add partial auth support
https://jira.corp.stripe.com/browse/TERMINAL-45163
Select one:
> Add partial auth support

- android/gradle.properties
- dev-app/android/build.gradle
Update kotlin to 2.0.0
our Kotlin need to upgrade to 2.1.0 otherwise the unit-test will fail, ci ref:
https://app.bitrise.io/build/a5921e2e-2502-4845-92d0-3db40f12613e
Select one:
> Update kotlin to 2.0.0

- .detoxrc.json
- bitrise.yml
- package.json
Update ios config to xcode 16
Update ios config to xcode 16 
Select one:
> Update ios config to xcode 16

- src/types/index.ts
Add cardDetails type in PaymentMethodDetails
https://jira.corp.stripe.com/browse/TERMINAL-45166
Select one:
> Add cardDetails in PaymentMethodDetails RN layer

- example-app/package.json
- example-app/yarn.lock
Add rnx-align-deps to example app
Add rnx-align-deps to example app so we can do faster upgrade in the future
Select one:
> Add rnx-align-deps to example app

- dev-app/src/screens/CollectCardPaymentScreen.tsx
Add missing onback callback for didRequestReaderDisplayMessage event
https://jira.corp.stripe.com/browse/RUN_TERMINAL_SDK-2156
Select one:
> Add missing onback callback for didRequestReaderDisplayMessage event

- android/src/main/java/com/stripeterminalreactnative/StripeTerminalReactNativeModule.kt
- dev-app/src/screens/RefundPaymentScreen.tsx
- ios/StripeTerminalReactNative.swift
- src/types/index.ts
Add metadata to RefundParams
https://jira.corp.stripe.com/browse/TERMINAL-47852
Select one:
> Add metadata to RefundParams

- dev-app/ios/Podfile.lock
- stripe-terminal-react-native.podspec
Keep up with native releases
Select one:
> Bump ios to 4.6.1

- dev-app/src/screens/CollectCardPaymentScreen.tsx
> Fix dev-app Android implementation for recollect after decline 

- .github/ISSUE_TEMPLATE/bug_report.md
- dev-app/ios/Podfile.lock
- package.json
> Bump versions for beta.27

- bitrise.yml
Updates Bitrise workflow from using SSH to using Github Apps 
KTLO
This PR is the test
Select one:
> Switch Bitrise to Github Apps integration 

- dev-app/src/components/AlertDialog.tsx
- dev-app/src/screens/SetupIntentScreen.tsx
Change var to let in ts file
Both `var` and `let` are variable in typescript but `let` is much preferred as the scope is determined. 
Hence I change all the usage to `let` in this pr.
Select one:
> Change var to let in ts file
